name: Deploy vuepress Site to Github Pages on main Branch

on:
  push:
    branches:
      - vuepress

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2  # v2 does not have submodules option now
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14'
            
      # 如果缓存没有命中，安装依赖
      - name: Install dependencies
        run: npm install --frozen-lockfile
        
      # 运行构建脚本
      - name: Build VuePress site
        run: npm run docs:build

      # 部署到GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }} # 这里的 ACTIONS_DEPLOY_KEY 则是上面设置 Private Key的变量名
          external_repository: wzliy/interviewGuide # Pages 远程仓库 
          destination_dir: docs # 仓库子目录
          publish_dir: docs/.vuepress/dist
          publish_branch: main  # deploying branch
          keep_files: false # remove existing files
          commit_message: ${{ github.event.head_commit.message }}
